image: ubuntu:latest
 
stages:
 - build
 - test
 
before_script:
 - echo "Before script install this on ubuntu image "
 - apt update && apt install build-essential && apt install splint && apt install valgrind && apt install curl

build_job:
 stage: build
 only:
   - main
 script:  
    - make
    - pwd  
     
 artifacts:
   expire_in: 365 days   //save the binary which needed while test the application, and it can be downloaded from GitLab
   paths:
      - bin

test_job:
 stage: test
 only:
   - main
 script:
    - pwd  
    - cd test
    - chmod -R 777 *
    - ./runTests.sh
   
 dependencies:
   - build_job
